server:
  port: 8083

spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:"

  r2dbc:
    url: jdbc:postgresql://localhost:2910/auth_db
    username: postgres
    password: zarina29
    pool:
      enabled: true
      initial-size: 10
      max-size: 20

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  #secret: "sY4h8d7skjdh32JHGjasd98h2734jhsaDhjkY8y3hJShd72jashDJH=="
  secret: "your-secure-random-secret-key-which-is-at-least-32-characters"
  expiration: 3600000  # 1 час в миллисекундах

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
