server:
  port: 8082

spring:
  application:
    name: inventory-service
  r2dbc:
    url: r2dbc:postgresql://localhost:2910/inventory_db
    username: postgres
    password: zarina29
  sql:
    init:
      mode: always
  cloud:
    loadbalancer:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

feifn:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
      authService:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        waitDurationInOpenState: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      circuitbreakers:
        enabled: true


logging:
  level:
    root: INFO
    org.springframework.cloud.openfeign: DEBUG
    com.springeasystock.inventoryservice: DEBUG
