server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:postgresql://localhost:2910/order_db
    username: postgres
    password: zarina29
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "sY4h8d7skjdh32JHGjasd98h2734jhsaDhjkY8y3hJShd72jashDJH=="

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
      authService:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
